# Generated by Django 5.1.1 on 2024-10-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(default=0, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ais.teachers'),
        ),
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone_number',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
