# Generated by Django 5.1.1 on 2024-10-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_students_email_students_name_students_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
    ]
